const express = require('express')
const router = express.Router()
const UserController = require('../controllers/AuthController')
const isAuth = require('../middlewares/isAuth')
const isAdmin = require('../middlewares/isAdmin')

router.post('/register', UserController.CreateUser)
router.post('/login', UserController.UserLogin)
router.post('/Adminlogin', UserController.AdminLogin)
router.post('/ApplyCoupon', isAuth, UserController.ApplyCoupon)
router.post('/Cash/CreateOrder', isAuth, UserController.CreateOrder)
router.get('/refresh', UserController.RefershTokenHandler)
router.get('/AllUsers', isAuth, isAdmin, UserController.getAllUSers)
router.get('/logout', isAuth, UserController.LogOutUser)
router.get('/wishlist', isAuth, UserController.GetWishList)
router.get('/GetCart', isAuth, UserController.GetUserCart)
router.get('/getOrders', isAuth, UserController.GetOrders)
router.get('/:id', isAuth, isAdmin, UserController.getSingleUser)
router.put('/update', isAuth, UserController.UpdateUser)
router.put('/blockuser/:id', isAuth, isAdmin, UserController.BlockUser)
router.put('/unblockuser/:id', isAuth, isAdmin, UserController.unBlockUser)
router.put('/changePassword', isAuth, UserController.changeUserPassword)
router.put('/AddAddress', isAuth, UserController.AddAddress)
router.put('/cart', isAuth, UserController.AddtoCart)
router.put('/updateOrderStatus/:id', isAuth, isAdmin, UserController.UpdateOrderStatus)
router.delete('/emptyCart', isAuth, UserController.EmptyCart)
router.delete('/:id', isAuth, isAdmin, UserController.DeleteSingleUser)


module.exports = router